
services:
  jenkins:
    image: jenkins/jenkins:lts
  
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins

  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - database

volumes:
  jenkins-data:
  postgres-data:

networks:
  jenkins:
  database:
name: prosperous